#!/usr/bin/env bash
# Builds an ARM64 libsteam_api.so in which every Steamworks entry point returns 0 ("Steam is not running").
set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "Usage: build.sh NDK_ROOT OUT_DIR" >&2
    exit 2
fi

ndk_root="$(cd "$1" && pwd)"
out_dir="$2"
here="$(cd "$(dirname "$0")" && pwd)"
android_api="${ANDROID_API:-21}"
host_tag="linux-x86_64"
if [[ "$(uname -s)" == Darwin* ]]; then
    host_tag="darwin-x86_64"
fi
clang="$ndk_root/toolchains/llvm/prebuilt/$host_tag/bin/aarch64-linux-android${android_api}-clang"
[[ -x "$clang" ]] || { echo "ERROR: tool not found: $clang" >&2; exit 3; }

mkdir -p "$out_dir"
source_file="$out_dir/steam_api_stub.generated.c"
{
    echo "/* Generated by tools/mono-arm64/steam-stub/build.sh. Do not edit. */"
    echo "#define RD_STEAM_STUB(name) __attribute__((visibility(\"default\"))) long name(void) { return 0; }"
    tr -d '\r' < "$here/steam_api_exports.txt" | sed -e '/^$/d' -e 's/.*/RD_STEAM_STUB(&)/'
} > "$source_file"

"$clang" -std=c11 -Wall -Wextra -Werror -O1 -fPIC -shared \
    -Wl,-soname,libsteam_api.so -Wl,-z,max-page-size=16384 \
    "$source_file" -o "$out_dir/libsteam_api.so"
rm -f "$source_file"

echo "STEAM_API_STUB verdict=BUILT exports=$(grep -c . "$here/steam_api_exports.txt") output=$out_dir/libsteam_api.so"
