using System.Text;

if (args.Length is < 2 or > 3)
{
    Console.Error.WriteLine("usage: IcallThunkGen INPUT_TSV OUTPUT_C [LIMIT]");
    return 2;
}

if (args.Length == 3 && !int.TryParse(args[2], out _))
{
    Console.Error.WriteLine("LIMIT must be a positive integer");
    return 2;
}
int limit = args.Length == 3 ? int.Parse(args[2]) : int.MaxValue;
if (limit < 1)
{
    Console.Error.WriteLine("LIMIT must be a positive integer");
    return 2;
}

string[] lines = File.ReadAllLines(args[0]);
if (lines.Length == 0 || lines[0] != "assembly\tname\tinstance\treturn\tparameters\tabi")
{
    Console.Error.WriteLine("input is not an IcallAudit TSV");
    return 3;
}

var rows = lines.Skip(1)
    .Select(ParseRow)
    .Where(row => row.Assembly.StartsWith("UnityEngine.", StringComparison.Ordinal))
    .OrderBy(row => row.Name, StringComparer.Ordinal)
    .Take(limit)
    .ToArray();

if (rows.Length == 0 || rows.Any(row => row.Abi.Contains('?')))
{
    Console.Error.WriteLine("input has no usable Unity rows or contains an unknown ABI type");
    return 4;
}

string? duplicate = rows.GroupBy(row => row.Name, StringComparer.Ordinal)
    .FirstOrDefault(group => group.Count() > 1)?.Key;
if (duplicate is not null)
{
    Console.Error.WriteLine($"duplicate registration name: {duplicate}");
    return 5;
}

var output = new StringBuilder();
output.AppendLine("/* Generated by IcallThunkGen. Do not edit. */");
output.AppendLine("#include <stdint.h>");
output.AppendLine("#include <string.h>");
output.AppendLine("#include \"callback.h\"");
output.AppendLine();
output.AppendLine("typedef struct rd_mono_icall_entry_s {");
output.AppendLine("    const char* name;");
output.AppendLine("    const char* abi;");
output.AppendLine("    uintptr_t* guest;");
output.AppendLine("    void* host;");
output.AppendLine("} rd_mono_icall_entry_t;");
output.AppendLine();

for (int index = 0; index < rows.Length; index++)
    EmitThunk(output, rows[index], index);

output.AppendLine("static rd_mono_icall_entry_t rd_mono_icalls[] = {");
for (int index = 0; index < rows.Length; index++)
{
    Row row = rows[index];
    output.AppendLine(
        $"    {{\"{EscapeCString(row.Name)}\", \"{row.Abi}\", &rd_icall_guest_{index:D5}, (void*)rd_icall_thunk_{index:D5}}},");
}
output.AppendLine("};");
output.AppendLine();
output.AppendLine("static void* rd_mono_icall_bind(const char* name, uintptr_t guest)");
output.AppendLine("{");
output.AppendLine("    int low = 0;");
output.AppendLine("    int high = (int)(sizeof(rd_mono_icalls) / sizeof(rd_mono_icalls[0])) - 1;");
output.AppendLine("    while (low <= high) {");
output.AppendLine("        int middle = low + (high - low) / 2;");
output.AppendLine("        int order = strcmp(name, rd_mono_icalls[middle].name);");
output.AppendLine("        if (order < 0) high = middle - 1;");
output.AppendLine("        else if (order > 0) low = middle + 1;");
output.AppendLine("        else {");
output.AppendLine("            *rd_mono_icalls[middle].guest = guest;");
output.AppendLine("            return rd_mono_icalls[middle].host;");
output.AppendLine("        }");
output.AppendLine("    }");
output.AppendLine("    return NULL;");
output.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(args[1]))!);
File.WriteAllText(args[1], output.ToString(), new UTF8Encoding(false));
Console.Error.WriteLine($"ICALL_THUNK_GEN methods={rows.Length} bytes={output.Length}");
return 0;

static Row ParseRow(string line)
{
    string[] fields = line.Split('\t');
    if (fields.Length != 6)
        throw new InvalidDataException($"malformed TSV row: {line}");
    return new Row(fields[0], fields[1], fields[5]);
}

static void EmitThunk(StringBuilder output, Row row, int index)
{
    char returnCode = row.Abi[0];
    string argumentCodes = row.Abi[2..];
    string parameters = argumentCodes.Length == 0
        ? "void"
        : string.Join(", ", argumentCodes.Select((code, i) => $"{CType(code)} a{i}"));
    string arguments = string.Join(", ", Enumerable.Range(0, argumentCodes.Length).Select(i => $"a{i}"));
    string callArguments = arguments.Length == 0 ? string.Empty : $", {arguments}";

    output.AppendLine($"static uintptr_t rd_icall_guest_{index:D5};");
    output.AppendLine($"static {CType(returnCode)} rd_icall_thunk_{index:D5}({parameters})");
    output.AppendLine("{");
    string call = returnCode is 'f' or 'd'
        ? $"RunFunctionFmtD(rd_icall_guest_{index:D5}, \"{argumentCodes}\"{callArguments})"
        : $"RunFunctionFmt(rd_icall_guest_{index:D5}, \"{argumentCodes}\"{callArguments})";
    if (returnCode == 'v')
        output.AppendLine($"    {call};");
    else
        output.AppendLine($"    return ({CType(returnCode)}){call};");
    output.AppendLine("}");
    output.AppendLine();
}

static string CType(char code) => code switch
{
    'v' => "void",
    'p' => "void*",
    'i' => "int32_t",
    'u' => "uint32_t",
    'I' => "int64_t",
    'U' => "uint64_t",
    'f' => "float",
    'd' => "double",
    _ => throw new InvalidDataException($"unsupported ABI code: {code}")
};

static string EscapeCString(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

internal sealed record Row(string Assembly, string Name, string Abi);
