using System.Text;

if (args.Length is < 2 or > 3)
{
    Console.Error.WriteLine("usage: IcallThunkGen INPUT_TSV OUTPUT_C [LIMIT]");
    return 2;
}

if (args.Length == 3 && !int.TryParse(args[2], out _))
{
    Console.Error.WriteLine("LIMIT must be a positive integer");
    return 2;
}
int limit = args.Length == 3 ? int.Parse(args[2]) : int.MaxValue;
if (limit < 1)
{
    Console.Error.WriteLine("LIMIT must be a positive integer");
    return 2;
}

string[] lines = File.ReadAllLines(args[0]);
if (lines.Length == 0 || lines[0] != "assembly\tname\tinstance\treturn\tparameters\tabi")
{
    Console.Error.WriteLine("input is not an IcallAudit TSV");
    return 3;
}

var rows = lines.Skip(1)
    .Select(ParseRow)
    .Where(row => row.Assembly.StartsWith("UnityEngine.", StringComparison.Ordinal))
    .OrderBy(row => row.Name, StringComparer.Ordinal)
    .Take(limit)
    .ToArray();

if (rows.Length == 0 || rows.Any(row => row.Abi.Contains('?')))
{
    Console.Error.WriteLine("input has no usable Unity rows or contains an unknown ABI type");
    return 4;
}

string? duplicate = rows.GroupBy(row => row.Name, StringComparer.Ordinal)
    .FirstOrDefault(group => group.Count() > 1)?.Key;
if (duplicate is not null)
{
    Console.Error.WriteLine($"duplicate registration name: {duplicate}");
    return 5;
}

var output = new StringBuilder();
output.AppendLine("/* Generated by IcallThunkGen. Do not edit. */");
output.AppendLine("#include <stdint.h>");
output.AppendLine("#include <string.h>");
output.AppendLine("#include \"callback.h\"");
output.AppendLine("/*");
output.AppendLine(" * The includer supplies the bridge: rd_icall_frame_t, rd_icall_enter(frame, index), rd_icall_leave() and");
output.AppendLine(" * rd_icall_float_result(). rd_icall_leave() returns nonzero when the guest raised a managed exception;");
output.AppendLine(" * the result is then discarded and Mono throws the pending exception in managed code.");
output.AppendLine(" */");
output.AppendLine("#ifndef RD_MONO_ICALL_BRIDGE_DEFINED");
output.AppendLine("#include \"rd_mono_icall_bridge.h\"");
output.AppendLine("#endif");
output.AppendLine();
output.AppendLine("/* Thunk index == position in rd_mono_icalls[]; the bridge can keep per-call statistics by it. */");
output.AppendLine($"enum {{ RD_MONO_ICALL_COUNT = {rows.Length} }};");
output.AppendLine();
output.AppendLine("typedef struct rd_mono_icall_entry_s {");
output.AppendLine("    const char* name;");
output.AppendLine("    const char* abi;");
output.AppendLine("    uintptr_t* guest;");
output.AppendLine("    void* host;");
output.AppendLine("} rd_mono_icall_entry_t;");
output.AppendLine();

for (int index = 0; index < rows.Length; index++)
    EmitThunk(output, rows[index], index);

output.AppendLine("static rd_mono_icall_entry_t rd_mono_icalls[] = {");
for (int index = 0; index < rows.Length; index++)
{
    Row row = rows[index];
    output.AppendLine(
        $"    {{\"{EscapeCString(row.Name)}\", \"{row.Abi}\", &rd_icall_guest_{index:D5}, (void*)rd_icall_thunk_{index:D5}}},");
}
output.AppendLine("};");
output.AppendLine();
output.AppendLine("static void* rd_mono_icall_bind(const char* name, uintptr_t guest)");
output.AppendLine("{");
output.AppendLine("    int low = 0;");
output.AppendLine("    int high = (int)(sizeof(rd_mono_icalls) / sizeof(rd_mono_icalls[0])) - 1;");
output.AppendLine("    while (low <= high) {");
output.AppendLine("        int middle = low + (high - low) / 2;");
output.AppendLine("        int order = strcmp(name, rd_mono_icalls[middle].name);");
output.AppendLine("        if (order < 0) high = middle - 1;");
output.AppendLine("        else if (order > 0) low = middle + 1;");
output.AppendLine("        else {");
output.AppendLine("            *rd_mono_icalls[middle].guest = guest;");
output.AppendLine("            return rd_mono_icalls[middle].host;");
output.AppendLine("        }");
output.AppendLine("    }");
output.AppendLine("    return NULL;");
output.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(args[1]))!);
File.WriteAllText(args[1], output.ToString(), new UTF8Encoding(false));
Console.Error.WriteLine($"ICALL_THUNK_GEN methods={rows.Length} bytes={output.Length}");
return 0;

static Row ParseRow(string line)
{
    string[] fields = line.Split('\t');
    if (fields.Length != 6)
        throw new InvalidDataException($"malformed TSV row: {line}");
    return new Row(fields[0], fields[1], fields[5]);
}

static void EmitThunk(StringBuilder output, Row row, int index)
{
    char returnCode = row.Abi[0];
    string argumentCodes = row.Abi[2..];
    string parameters = argumentCodes.Length == 0
        ? "void"
        : string.Join(", ", argumentCodes.Select((code, i) => $"{CType(code)} a{i}"));
    string arguments = string.Join(", ", Enumerable.Range(0, argumentCodes.Length).Select(i => $"a{i}"));
    string callArguments = arguments.Length == 0 ? string.Empty : $", {arguments}";
    // Narrow integers travel as full 32-bit values: C promotes them to int with the right extension, and
    // the x86-64 callee may rely on the caller having extended them (clang does).
    string format = new string(argumentCodes.Select(code => code switch
    {
        'c' or 'w' => 'i',
        'C' or 'W' => 'u',
        _ => code
    }).ToArray());
    string guest = $"rd_icall_guest_{index:D5}";

    output.AppendLine($"static uintptr_t {guest};");
    output.AppendLine($"static {CType(returnCode)} rd_icall_thunk_{index:D5}({parameters})");
    output.AppendLine("{");
    output.AppendLine("    rd_icall_frame_t frame;");
    output.AppendLine($"    rd_icall_enter(&frame, {index});");
    switch (returnCode)
    {
        case 'v':
            output.AppendLine($"    RunFunctionFmt({guest}, \"{format}\"{callArguments});");
            output.AppendLine("    rd_icall_leave(&frame);");
            break;
        case 'd':
            output.AppendLine($"    double ret = RunFunctionFmtD({guest}, \"{format}\"{callArguments});");
            output.AppendLine("    if (rd_icall_leave(&frame)) return 0;");
            output.AppendLine("    return ret;");
            break;
        case 'f':
            // RunFunctionFmtD reads xmm0 as a double; a float result only occupies its low 32 bits.
            output.AppendLine($"    RunFunctionFmt({guest}, \"{format}\"{callArguments});");
            output.AppendLine("    float ret = rd_icall_float_result(&frame);");
            output.AppendLine("    if (rd_icall_leave(&frame)) return 0;");
            output.AppendLine("    return ret;");
            break;
        default:
            output.AppendLine($"    uint64_t ret = RunFunctionFmt({guest}, \"{format}\"{callArguments});");
            output.AppendLine("    if (rd_icall_leave(&frame)) return 0;");
            output.AppendLine($"    return ({CType(returnCode)})ret;");
            break;
    }
    output.AppendLine("}");
    output.AppendLine();
}

static string CType(char code) => code switch
{
    'v' => "void",
    'p' => "void*",
    'c' => "int8_t",
    'C' => "uint8_t",
    'w' => "int16_t",
    'W' => "uint16_t",
    'i' => "int32_t",
    'u' => "uint32_t",
    'I' => "int64_t",
    'U' => "uint64_t",
    'f' => "float",
    'd' => "double",
    _ => throw new InvalidDataException($"unsupported ABI code: {code}")
};

static string EscapeCString(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

internal sealed record Row(string Assembly, string Name, string Abi);
